export const curiaList = [
  {
    name: "Mary Mediatrix of All Graces Curia",
    description: "This is the Curia for North Calgary",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Queen of the Most Holy Rosary Curia",
    description: "This is the Curia for South Calgary",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Our Lady of Perpetual Help Curia",
    description: "This is the Curia for the Korean Community",
    email: "",
    phone: "",
    address: "",
  },
];

export const juniorPraesidiumList = [
  {
    name: "Sancta Maria Junior Praesidium",
    parish: "St. Anthony's Parish",
    email: "audmartis@hotmail.com",
    phone: "4032380448",
    address: "5340-4 St SW, Calgary AB T2V 0Z5",
  },
  {
    name: "Mary Cause of Our Joy, Junior Praesidium",
    parish: "Holy Spirit Church Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Mother of Our Life Junior Praesidium",
    parish: "St. Luke's Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Our Lady of Angels, Junior Praesdium",
    parish: "St. Patrick's Parish",
    email: "erminec@hotmail.com",
    phone: "4035549655",
    address: "1414 Shawnessy Blvd SW, Calgary AB T2Y 2L7",
  },
];


export const southPraesidiumList = [
  {
    name: "Mother of Divine Grace",
    parish: "St. Anthony's Parish",
    email: "annapabilando@gmail.com",
    phone: "4033833113",
    address: "5340-4 St SW, Calgary AB T2V 0Z5",
  },
  {
    name: "Mary, Queen of Victory",
    parish: "St. Patrick's Parish",
    email: "erminecummings@gmail.com",
    phone: "4035549655",
    address: "1414 Shawnessy Blvd SW, Calgary AB T2Y 2L7",
  },
  {
    name: "Mary, Mother of God",
    parish: "Our Lady of Fatima Parish",
    email: "chrismina_adamson@yahoo.ca",
    phone: "4034017120",
    address: "4747 30 St SE, Calgary AB T2B 3K5",
  },
  {
    name: "Virgin of Virgins",
    parish: "St. Vincent of Liem Church",
    email: "",
    phone: "",
    address: "2414 48 St SE, Calgary AB T2B 1M4",
  },
  {
    name: "Our Lady of Assumption",
    parish: "Holy Spirit Church",
    email: "jinwankwo84@gmail.com",
    phone: "4036135262",
    address: "10827 24 St SW, Calgary AB T2W 2Z2",
  },
  {
    name: "Immaculate Mary",
    parish: "St. Vincent of Liem Church",
    email: "",
    phone: "",
    address: "2414 48 St SE, Calgary AB T2B 1M4",
  },
  {
    name: "Mother of Divine Mercy",
    parish: "St. Patrick's Church",
    email: "aguilamina@gmail.com",
    phone: "4036671064",
    address: "1414 Shawnessy Blvd SW, Calgary AB T2Y 2L7",
  },
  {
    name: "Mater Misericordiae",
    parish: "St. Francis Xavier Chaplaincy",
    email: "affectuminflamma@gmail.com",
    phone: "4034624842",
    address: "219 – 18 Ave SW, Calgary AB T2S 0C2",
  },
  {
    name: "Star of the Sea",
    parish: "St. Patrick's Parish",
    email: "jecintaudeh@gmail.com",
    phone: "5877182160",
    address: "1414 Shawnessy Blvd SW, Calgary AB T2Y 2L7",
  },
  {
    name: "Our Lady of Perpetual Help",
    parish: "St. Bonaventure Parish",
    email: "thomasumi31@gmail.com",
    phone: "5874386625",
    address: "1600 Acadia Drive SE, Calgary AB T2J 3B3",
  },
  {
    name: "Immaculate Conception",
    parish: "St. James Parish",
    email: "recrisem.aguilar@yahoo.com",
    phone: "",
    address: "5504 20 St SW, Calgary AB T3E 1R2",
  },
  {
    name: "Our Lady of Grace",
    parish: "St. Martha's Parish, Lethbridge",
    email: "deborah.huneault@gmail.com",
    phone: "4037159212",
    address: "355 Columbia Blvd W, Lethbridge AB T1K 5Y8",
  },
];

export const northPraesidiumList = [
  {
    name: "Mary, Queen of Peace",
    parish: "St. Mark's Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Mary Immaculate",
    parish: "St. Mark's Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Immaculate Heart of Mary",
    parish: "Our Lady of Perpetual Help Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Mary, Mother of Good Counsel",
    parish: "Ascension Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Mystical Rose",
    parish: "St. Patrick's Parish (Medicine Hat)",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Mary, Ark of the Covenant",
    parish: "St. Luke's Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Seat of Wisdom",
    parish: "St. Luke's Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Spiritual Vessel",
    parish: "St. Pius X Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Our Lady of Visitation",
    parish: "St. Thomas More Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Queen of Martyrs",
    parish: "Canadian Martyrs Parish",
    email: "",
    phone: "",
    address: "",
  },
  {
    name: "Mary Help of the Sick",
    parish: "St. Mary's Church (Brooks) Parish",
    email: "",
    phone: "",
    address: "",
  },
];
